package com.careerlauncher.gkninja.network

/**
 * Created by Navjot Singh
 * on 2/3/19.
 */
object NetworkConstants {
    //    Key Constants
    const val CODE_SUCCESS = 200
    const val RESULT_SUCCESS = "Success"
    var BASE_URL = "https://www.aspiration.link/endpoints/"

    //public static final String BASE_URL = "https://www.aspiration.ai/endpoints/";
    var MAIN_BASE_URL = "https://www.aspiration.link/"

    //    Network call end-points
    const val END_POINT_LOGIN = "login/"
    const val END_POINT_GET_PASSWORD = "verifyEmail/"
    const val END_POINT_GET_USERNAME = "VerifyUserName/"
    const val END_POINT_VERIFY_USERNAME = "sendUserNameEmail/"
    const val END_POINT_USER_DETAILS = "UserDetail/"

    const val END_POINT_REGISTRATION = "registration/"
    const val END_POINT_LOGOUT = "logout/"
    const val END_POINT_REGISTER = "registration/"
    const val END_POINT_SIS_AUTHORIZE = "sisAuthorize/"
    const val END_POINT_MBA_SIS = "MBA/sis/"
    const val END_POINT_TEST_TOPIC = "/sis/topicTests/"
    const val END_POINT_TEST_TOPIC_V2 = "/sis/GateTopicTests/"
    const val END_POINT_TEST_TOPIC_V3 = "/sis/GreDrillsTest/"
    const val END_POINT_TEST_SECTION_V4 = "/sis/Exercise/"
    const val END_POINT_Chapter_TEST = "/sis/ChapterTests/"
    const val END_POINT_Chapter_TEST_V2 = "/sis/ChapterTest/"
    const val END_POINT_TOPIC_TEST_V3 = "/sis/GreDrillsTest/"
    const val END_POINT_PRELIM_TEST = "/sis/PrelimsTests/"
    const val END_POINT_PRACTICE_TEST_LIST = "/sis/schoolTestList/"
    const val END_POINT_SECTION_TEST_LAW = "/sis/SectionalTestGYM/"
    const val END_POINT_PRACTICE_TEST_LAW = "/sis/newPracticeTests/"
    const val END_POINT_SECTIONAL_TEST = "/sis/TestGymClassic/"
    const val END_POINT_SECTIONAL_TEST_V2 = "/sis/TestGymSection/"
    const val END_POINT_READ_EBOOK = "/sis/ReadEbook/"
    const val END_POINT_READ_EBOOK_V2 = "/sis/elib/"
    const val END_POINT_PDP_HOME = "/sis/pdp/"
    const val END_POINT_PDP_WHO_AM_I = "/sis/pdp/who-am-i/"
    const val END_POINT_PDP_BOOK_PI = "/sis/pdp/book-my-pi/"
    const val END_POINT_PDP_POWER = "/sis/pdp/power-pdp/"
    const val END_POINT_PDP_KNOWLEDGE = "/sis/pdp/knowledge-sessions/"
    const val END_POINT_PDP_ONLINE_EBOOK_SESSION = "/sis/pdp/OnlinePDPVideoSession/"
    const val END_POINT_PDP_SHARE_EXP = "/sis/pdp/ViewShareExp/"
    const val END_POINT_PDP_SHARE_FORM = "/sis/pdp/FeedbackForm/"
    const val END_POINT_PDP_VIEW_OLD_EXP = "/sis/pdp/ShowPreviousExp/"
    const val END_POINT_SIS_PART = "/sis/"
    const val END_POINT_PAYMENT_DETAIL = "/sis/PaymentDetail/"
    const val END_POINT_DIGITAL_ID_CARD = "/sis/studDID/"
    const val END_POINT_VIDEOS = "/sis/CurrentVideo/"
    const val END_POINT_VIDEOS_V2 = "/sis/OnlineVideo/"
    const val END_POINT_TOOLS = "/sis/BSchoolZone/"
    const val END_POINT_ACAD_DETAIL = "/sis/AcadDetail/"
    const val END_POINT_QUICK_LINKS = "/quickLinks/"
    const val END_POINT_PERSONAL_DETAIL = "/sis/PersonalDetail/"
    const val END_POINT_GET_PROFILE_ZONE = "/sis/ProfileZone/"
    const val END_POINT_MBAPROFILIZER = "/sis/profilizer/ViewBSchoolMatrixV2/"
    const val END_POINT_ARTICLE = "article/"
    const val END_POINT_RANKING_GK = "Games/"
    const val END_POINT_RANKING_LEGAL = "LegalZone/"
    const val END_POINT_VIEW_PERFORMANCE = "newtgtest/ViewSolutionsTest/"
    const val END_POINT_TOPIC_TEST_VIEW_BOOKMARK = "newtgtest/ViewTgymBmarkTest/"
    const val END_POINT_TOPIC_TEST_VIEW_INCORRECT_QUESTION = "newtgtest/ViewIncorrectQs/"
    const val END_POINT_WRITE_MOCKS = "/sis/Tests/"
    const val END_POINT_ONLINE_TEST = "/sis/mathsTest/"
    const val END_POINT_WRITE_MOCKS_ENGG = "/sis/Mocks1/"
    const val END_POINT_EXAM_INFORMATION = "/sis/ExamPatterns/"
    const val END_POINT_MOCKS_LIST = "/sis/Mocks/"
    const val END_POINT_MOCKS_LIST_FRM = "/sis/test/"
    const val END_POINT_MOCKS_LIST_V2 = "/sis/mockTests/"
    const val END_POINT_MOCKS_LIST_V3 = "/sis/FreeMock/"
    const val END_POINT_MOCKS_LIST_V4 = "/sis/MockTest/"
    const val END_POINT_SCHEDULES = "/sis/Schedules/"
    const val END_POINT_TEST_TOPIC_QUESTION_LIST = "/newtgtest/TakeDiagnosticTest/"
    const val END_POINT_TEST_TOPIC_RESET = "newtgtest/ResetTestGym/"
    const val END_POINT_STRENGTH_FINDER = "/sis/csb/CATScoreBooster/"
    const val END_POINT_UPDATE_STRENGTH_FINDER = "/sis/SCFForm/"
    const val END_POINT_SUBMIT_STRENGTH_FINDER = "/sis/InsUserStrength/"
    const val END_POINT_SECTION_TEST_SCORECARD = "/sis/ScoreCard/"
    const val END_POINT_CHAPTER_TEST_SCORECARD = "/sis/ChapterScoreCard/"
    const val END_POINT_CHAPTER_TEST_SOLUTION = "/sis/ChapterSolution/"
    const val END_POINT_CHAPTER_TEST_BOOKMARKS = "/sis/ChapterBookmarks/"
    const val END_POINT_SECTION_TEST_ACCURACY = "/sis/AccSelectGraph/"
    const val END_POINT_ENGLISH_USAGE_TEST = "/csat/sis/GK_Tests/ViewGDTestPaper/"
    const val END_POINT_SECTION_TEST_SOLUTION = "/sis/Solution/"
    const val END_POINT_SECTION_TEST_BOOMARKS = "/sis/Bookmarks/"
    const val END_POINT_MOCK_BOKMARKS = "/sis/AnalysisBookmarks/"
    const val END_POINT_CAT_MOCKS_ANALYSIS = "/sis/Analysis/"
    const val END_POINT_CAT_MOCKS_ANALYSIS_V2 = "/sis/analysis/"
    const val END_POINT_FINAL_SCORE_LIST = "newtgtest/ViewTGYMScoreCard/"
    const val END_POINT_VIDEO_ANALYSIS = "/sis/VideoAnalysis/"
    const val END_POINT_SECTIONAL_QUIZ_QUESTIONS = "/online/MBATestPaper/"
    const val END_POINT_SECTIONAL_QUIZ_QUESTIONS_UNIVERSAL = "MBA/online/MBATestPaper/"
    const val PRODUCT_SELECTION_ONLINE_URL = "https://www.careerlauncher.com/cl-online/"
    const val END_POINT_GRAMMAR_ZONE = "SisVocab/"
    const val EMAIL = "email"
    const val USERNAME = "username"
    const val PASSWORD = "password"
    const val REMEMBER_ME = "rememberMe"
    const val SOURCE = "source"
    const val IS_CAMPSIS = "isCampsis"
    const val REDIRECT_TO = "redirectTo"
    const val PROD_ID = "prodId"
    const val USER_ID = "userId"

    //Extras
    const val PDF_APK_URL =
        "https://www.careerlauncher.com/mapp/mobiquel/Career Launcher eBooks_v1.6.4_apkpure.com.apk"
    const val PDF_APK_NAME = "Career Launcher eBooks_v1.6.4_apkpure.com"
    const val END_POINT_BOOKING_PAGE = "/sis/resv1/"
    const val END_POINT_BOOKING_RULE = "/sis/resv1/Rules/"
    const val END_POINT_ADD_RESERVATION = "/sis/resv1/AddReservation/"
    const val END_POINT_CONTACT_US = "/sis/resv1/ContactUs/"
    const val END_POINT_MY_BOOKING = "/sis/resv1/ViewMyBooking/"
    const val END_POINT_CANCEL_BOOKING = "/sis/resv1/CancelReservation/"
    const val END_POINT_BOOK_MY_TEST = "/sis/resv1/ViewSession/"
    const val END_POINT_CAT_MOCKS_BOOKMARK = "/sis/ViewAllBookmarked/"
    const val END_POINT_CAT_MOCKS_DRILL_DOWN_ANALYSIS = "/sis/DrillDownAnalysis/"
    const val END_POINT_NON_CAT_MOCKS_ANALYSIS = "/sis/AnalysisNonCat/"
    const val END_POINT_TOPPERS = "/sis/Toppers/"
    const val END_POINT_REMOVE_BOOKMARK_CAT_MOCK_ANALYSIS = "/sis/RemoveBookmarked/"
    const val END_POINT_VIEW_SOLUTION_CAT_MOCK_ANALYSIS = "/sis/ViewSolutions/"
    const val END_POINT_CAT_MOCK_QUESTION_ANALYSIS = "/sis/QsAnalysis/"
    const val END_POINT_QS_ANALYSIS_SOLUTION = "/sis/ViewSolutions/"
    const val END_POINT_CAT_MOCK_SCORECARD = "/sis/procreview/"
    const val END_POINT_CAT_MOCK_DRILL_DOWN_ANALYSIS_BY_SET =
        "/sis/DrillDownAnalysisByQset/"
    const val END_POINT_CAT_MOCK_SHOW_MODULE_ANSWER = "/sis/ShowMockAnsDrill/"
    const val END_POINT_CAT_MOCK_BOOSTER_ANALYSIS = "/sis/BoosterAnalysis/"
    const val END_POINT_NIGHT_CLASSES_VIDEOS = "/sis/NCVideos/"
    const val END_POINT_AMICUS_BOT = "/sis/alexa/bot/"
    const val END_POINT_WEB_CAST_SESSIONS = "/sis/WebCastSessions/"
    const val END_POINT_WEB_INAR_SESSIONS = "/sis/WebinarVideos/"
    const val END_POINT_MOD = "/sis/MOD/"
    const val END_POINT_FUNDA_VIDEOS = "/sis/FundaBookVideos/"
    const val END_POINT_STRATEY_SESSIONS = "/sis/OnlineVideo/"
    const val END_POINT_GET_INSTRUCTION_DATA = "/online/MBATestValidator/"
    const val END_POINT_SUBMIT_TOPIC_TEST = "newtgtest/SubmitDiagnosticTestV1/"
    const val END_POINT_CAT_MOCKS_INSTRUCTION =
        "/endpoints/MBA/online/MBATestValidatorNew/"
    const val END_POINT_WRITE_MOCKS_QUESTION = "/endpoints/MBA/online/MBATestPaperNew/"
    const val END_POINT_WRITE_NON_CAT_MOCKS_QUESTION = "/online/NMATTestPaperV2/"
    const val END_POINT_GK_ARCHIVES = "GKArchives/"
    const val END_POINT_GK_QSET_TODAY_YESTERDAY = "GK/"
    const val END_POINT_GK_PAPERS = "GKPaper/"
    const val END_POINT_SUBMIT_GK_PAPERS = "SubmitGKPaper/"
    const val END_POINT_VIEW_GK_PAPERS_SOLUTION = "ViewSolution/"
    const val END_POINT_SUBMIT_SECTION_TEST = "/online/AcceptAnsNew/"
    const val END_POINT_SUBMIT_SECTION_TEST_GRE = "/online/AcceptAnsNewGRE/"
    const val END_POINT_SUBMIT_SECTION_TEST_GMAT = "/online/AcceptAnsNewGMAT/"
    const val END_POINT_MANAGEMENT_COMPASS = "/sis/ReadECompass/"
    const val END_POINT_COMPENDIUM = "/sis/Compendium/"
    const val END_POINT_COMPENDIUM_2 = "/sis/ElibStudyMaterial/"
    const val END_POINT_BSCHOOL_RANKING = "/sis/bschools/"
    const val END_POINT_NEWS_ARCHIEVE = "NewsArchive/"
    const val END_POINT_NEWS_ARCHIEVE_DETAIL = "NewsLetter/"
    const val END_POINT_ADD_TO_BOOKMARK = "/sis/AddBookmark/"
    const val END_POINT_ADD_TOPIC_TEST_BOOKMARK = "/newtgtest/AddToTGYMBookmark/"
    const val END_POINT_REMOVE_BOOKMARK = "/sis/RemoveBookmarked/"
    const val END_POINT_GK_GAME = "GKGame/"
    const val END_POINT_SUBMIT_GK_GAME = "GKGameUpdate/"
    const val END_POINT_VIEW_SCHEDULE = "/sis/resv1/ViewWeekSchedule/"
    const val END_POINT_BOOK_SLOT_OPEN_MOCK = "/sis/resv1/InsOpenMockLoc/"
    const val END_POINT_BOOK_SLOT_ADD_RESERVATION = "/sis/resv1/AddReservation/"
    const val END_POINT_BOOK_SLOT_MOCK_LOCATION = "/sis/resv1/ChkOpenMockLocation/"
    const val END_POINT_REMOVE_BOOKMARK_TOPIC_TEST = "newtgtest/RemoveTgymBmarked/"
    const val END_POINT_ADD_BOOKMARK_TOPIC_TEST = "newtgtest/AddToTGYMBookmark/"
    const val END_POINT_MOCK_VIDEO_ANALYSIS = "/sis/VideoAnalysis/"
    const val END_POINT_GET_RANDOM_TEST = "/LAW/sis/GenRandomTest/"
    const val END_POINT_SUBMIT_ENGLISH_TEST = "/csat/sis/GK_Tests/SubmitGDTestPaper/"
    const val END_POINT_GRAMMAR_ARCHIEVES = "/LAW/sis/GKArchives/"
    const val END_POINT_VOCAB_GAME = "VocabGame/"
    const val END_POINT_FACTS_GAME = "AIGKGame/"
    const val END_POINT_LEGAL_GAME = "LegalGame/"
    const val END_POINT_SUBMIT_VOCAB_GAME = "VocabGameUpdate/"
    const val END_POINT_SUBMIT_LEGAL_GAME = "LegalGameUpdate/"
    const val END_POINT_SUBMIT_FACTS_GAME = "AIGKGameUpdate/"
    const val END_POINT_RESET_TEST = "/sis/resetTest/"
    const val END_POINT_UPDATE_DETAILS = "/updateFamilyDetails/"
    const val END_POINT_MY_CLASS_BUTTONS = "/sis/MyClassZone/"
    const val END_POINT_MY_CLASS_DATA = "/sis/MyClass/"
    const val END_POINT_MY_ATTENDENCE = "/sis/MyAttandence/"
    const val END_POINT_REPORT_ERROR = "/sis/studentDB/"
    const val END_POINT_GET_DASHBOARD = "/dashboard/dashboard/"
    const val END_POINT_GET_NOTIFICATION = "/getAspNotification/"
    const val END_POINT_STATS = "/aspiration/"
    const val END_POINT_PRIVACY_POLICY = "privacy/"
    const val END_POINT_GET_BANNER_IMAGE = "getBannerURL/"
    const val END_POINT_INSERT_FEEDBACK = "feedback/insert/"
    const val END_POINT_VERSION_REGISTER = "version/register/"
    const val END_POINT_GET_APP_VERSION = "version/getVersion/"

    const val END_POINT_MATHAN_FEEDBACK = "FeedbackFormData/"
    const val END_POINT_MATHAN_SUBMIT_FEEDBACK = "SubmitFeedback/"
    const val END_POINT_GET_BANNER_CONTENT = "getBannerContent/"
    const val END_POINT_DASHBOARD_DATA = "/sis/AcadDetailFormNew/"
    const val END_POINT_SUBMIT_DETAIL = "/sis/InsStudDetailNew/"
    const val TRACK_APP_USAGE =
        "http://www.careerlauncher.com/mapp/mobiquel/InsMappUses.jsp"

    fun changeApiBaseUrl(newApiBaseUrl: String) {
        BASE_URL = newApiBaseUrl + "endpoints/"
        MAIN_BASE_URL = newApiBaseUrl
    }
}